### ISSUE TITLE
Release of 1.2.0

### ISSUE THREAD

**Issue by drmaas** [hyleung/ratpack-zipkin#20]
Are you planning on releasing 1.2.0 to nexus/bintray? I'd like to start using the `@Zipkin` annotation on an http client.

**Comment by hyleung** [comment]
@drmaas hoping to get to it in the next few days - just need to give it a look, update some docs, etc. Just merged some changes that includes a fix to the client, as well as a small change in the default behaviour (we're adding some default key value annotations, fixing up the keys, etc.).

**Comment by drmaas** [comment]
Awesome, I look forward to it!

**Comment by hyleung** [comment]
Done!

https://github.com/hyleung/ratpack-zipkin/releases/tag/1.2.0

**Comment by drmaas** [comment]
:1st_place_medal:
