### ISSUE TITLE
2.x - Add support for customizing tags on request/response

### ISSUE THREAD

**Issue by hyleung** [hyleung/ratpack-zipkin#27]
This is another feature that was in v1, but removed as part of #24. Users used to be able to inject their own logic for adding `KeyValueAnnotations` via module configuration. E.g.

```
config
    .serviceName("ratpack-demo")
    .requestAnnotations(request ->
        Lists.newArrayList(KeyValueAnnotation.create("uri", request.getUri()))
    )
    .responseAnnotations(response ->
        Lists.newArrayList(KeyValueAnnotation.create("foo", "bar"))
    );
```

[Update] Going to look at customizing tags first...

**Comment by codefromthecrypt** [comment]
Fyi i have work in progress calling these requestTags and responseTags.
Will ping on details but essentially resurrecting brave-http

**Comment by llinder** [comment]
With Brave 4.3.1 custom annotations can be provided through a custom `HttpParser` and overriding the `request(adapter, req, customizer)` and `response(adapter, res, error, customizer)` methods.

In these methods the `customizer` parameter is of type `SpanCustomizer` which allows users to add tags and annotations to the span.

Users can provide a custom `HttpParser` through the `ServerTracingModule` `clientParser` and `serverParser` configuration properties.

@hyleung do you think this sufficiently covers the ability to customize the span?

**Comment by hyleung** [comment]
@llinder yeah I think for now it's probably good enough. Or at least, we can defer until we get a better idea of how it "feels". Where I wanted to go with this was something more "typical" for Ratpack - i.e. using a lambda to customize the behavior.

**Comment by hyleung** [comment]
@adriancole are there any updates on the request/response Tag stuff?

> Fyi i have work in progress calling these requestTags and responseTags.
Will ping on details but essentially resurrecting brave-http

**Comment by codefromthecrypt** [comment]
> @adriancole <https://github.com/adriancole> are there any updates on the
> request/response Tag stuff?
>
> Fyi i have work in progress calling these requestTags and responseTags.
> Will ping on details but essentially resurrecting brave-http
>
>
https://github.com/openzipkin/brave/tree/master/instrumentation/http#span-data-policy
is latest and greatest

**Comment by hyleung** [comment]
Revisiting this after #52 - thinking if I do add something like this, it would be more straightforward to just have a function (or functions) that take a `SpanCustomizer` and let folks do whatever they like.
