### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by hyleung** [hyleung/ratpack-zipkin#32]
Placeholder issue for tracking things that need to be done for a 2.0.0 release:

- [x] Update to Brave 4
- [x] Update Readme/docs/examples

**Comment by hyleung** [comment]
@llinder originally there were a few things I figured we might want to include in the release. For example, bringing back some of the stuff you used to be able to configure in the module. But a) not sure if they're still necessary and b) the upgrade to Brave 4 is probably enough.

If you can think of anything else that might need to be done, polished, etc. let me know :)

Btw - I did a little testing: are you seeing client spans getting reported?

**[Update: Turns out my client spans were there, just not part of the same trace - see #36]**

**Comment by llinder** [comment]
@hyleung originally I thought we might want to bring back some of the HTTP abstractions.  Now that Brave 4 includes these I don't think there is anything else needed.  As far as configuration options I think the ServerTracingModule covers all of the major Tracing configuration options.

Once 2.0 is released I would like to revisit context propagation fixes for ParallelBatch.  That can probably wait until this is out though.

**Comment by hyleung** [comment]
@llinder re.

> I would like to revisit context propagation fixes for ParallelBatch. 

...is that related to your comments [here](https://github.com/hyleung/ratpack-zipkin/pull/35#discussion_r117399987) on #35 ?

**Comment by llinder** [comment]
@hyleung sorry for the delayed response.  Yes the changes in #35 covers my comment about ParallelBatch work.

What do you think about making a 2.0 release?  I would like to start using this in several services in proprod environments this week if possible.  Maybe a milestone release like 2.0.0-M1 until we get the docs up to date?

**Comment by hyleung** [comment]
@llinder I think the only other thing I wanted to do (other than update the README) is quickly test the ParallelBatch stuff. Other than that I think we're good to do a release in the next day or so. That sound good? If you want something sooner, I'm happy to do a milestone release today...

**Comment by llinder** [comment]
Thanks @hyleung... sometime in the next few days works for me.  Mostly I didn't want to put pressure on anyone to get docs or examples updated.  If we find that more time is needed for docs or testing then maybe we can revisit a milestone release in a couple days if necessary.

**Comment by hyleung** [comment]
@llinder had a quick test of the ParallelBatch stuff, works as advertised 😄 

Also did a quick pass to update the README and some Javadoc in #38

**Comment by hyleung** [comment]
Released v2.0.0!
