### ISSUE TITLE
Implement support for the stock Brave http server test suite

### ISSUE THREAD

**Issue by hyleung** [hyleung/ratpack-zipkin#43]
Ref: https://github.com/hyleung/ratpack-zipkin/issues/39#issuecomment-329670462

Similar work has already been done for supporting the stock http _client_ test suite.

**Comment by codefromthecrypt** [comment]
Thx for raising this. PS if you have any tests not upstream, please lemme
know. There are some edge cases we can help all the things pass. (FYI there
are both client and server tests in brave, and if we can rejig to make more
friendly to re-use lemme know)

**Comment by codefromthecrypt** [comment]
also PS we're starting to make end-to-end benchmarks, too
https://github.com/openzipkin/brave/pull/500

**Comment by hyleung** [comment]
@adriancole managed to get this working (had to add the ability to pass a `HttpTracing` to the module to make it work). There is one test that I'm having trouble with at the moment:

https://github.com/openzipkin/brave/blob/master/instrumentation/http-tests/src/main/java/brave/http/ITHttpServer.java#L114-L121

Do I need to explicitly set the Span's remote endpoint somewhere? I thought it might be done by `HttpServerHandler`:

https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpServerHandler.java#L83-L95

...but I don't think I'm hitting _either_ of those conditionals (not Zipkin V1 and no `X-Forwarded-For`) - which means remote endpoint is not set. 

**[Update]**  Think I know what I need to do. Need to override `parseClientAddress` in my `HttpServerAdapter`.

**Comment by codefromthecrypt** [comment]
I think you got these, but lemme know if you haven't :)
