### ISSUE TITLE
Action being executed multiple times in HttpClient.request

### ISSUE THREAD

**Issue by ptong-samsung** [hyleung/ratpack-zipkin#46]
https://github.com/hyleung/ratpack-zipkin/blob/master/src/main/java/ratpack/zipkin/internal/ZipkinHttpClientImpl.java#L85

Action is executed twice, once in action.append, and once in wrapped request.
If the user is using functions like requestSpec.headers.add, duplicate headers will be added to the request. This causes error in some of the server. For example, AWS ELB will return 400 when it founds multiple Authroization header.

**Comment by hyleung** [comment]
@ptong-samsung thanks for reporting this - do you have any workarounds available to you that can mitigate the issue? As you can probably tell from looking at that code, there was a fair bit of yak shaving required to get client tracing working so there's a chance we can't yak-shave our way out of this one. Ratpack *has* added support for client request/response interceptors and at some point we were going to revisit our client tracing implementation in this library to make use of that (#44).

**Comment by ptong-samsung** [comment]
@hyleung Thanks. Yes we just changing everything to use headers.set so its fine. Just want to create this to keep trace of the issue.

**Comment by llinder** [comment]
I see whats happening here.  I think I can fix this quick.

**Comment by llinder** [comment]
For our use case it would be good to get this fixed before Ratpack 1.6 with interceptors since we still have some code bases one 1.4.5 and updating takes a bit of time.

**Comment by hyleung** [comment]
@llinder I've merged and done a release that includes your fix (#47) - it's still propagating out to Maven central etc, the version is 2.1.0. I'm a little behind on day-job stuff, but when I get a minute, I'll write up some quick release notes (really it's just #47 and #42/#27)

cc/ @ptong-samsung
