### ISSUE TITLE
Move ratpack-zipkin to OpenZipkin

### ISSUE THREAD

**Issue by hyleung** [hyleung/ratpack-zipkin#59]
Following some email discussions with @adriancole and @llinder - I wanted to create an issue to start enumerating the things that would need to be done in order to move `ratpack-zipkin` into OpenZipkin.  The primary motivation for this move is to keep the project moving along w/o me being a bottleneck for releases, etc. 

Things that need to be done:
- [x] migrate from Gradle to Maven(?)

**Comment by hyleung** [comment]
Hmm....I haven't touched this project in white a while now. More generally, I haven't been able to keep up to date with where Zipkin/Brave is heading. Wondering if it's worth just getting things in a state where the project *could* be moved.

Other than just migrating from Gradle to Maven, are there any other things that need to be sorted out?

**Comment by codefromthecrypt** [comment]
not aware of anything else unless package names etc would be changed.

will defer to you and smart things folks

**Comment by llinder** [comment]
I've been meaning to get to this.  Going to try and push it up the priority list.

**Comment by hyleung** [comment]
@llinder happy to help with this - bit of a lull after a busy period at work, but quite possibly ramping up again soon - which is why it occurred to me that this might be a good time to get this squared away.

**Comment by hyleung** [comment]
> I've been meaning to get to this. Going to try and push it up the priority list.

@llinder I've made a stab at this in #63. Whenever you get the chance, take a peek and see if there's anything I'm missing (or things you can think of that I should try to test).

**Comment by codefromthecrypt** [comment]
ps we should decide if this will be contrib or want this to go into ASF ;)

**Comment by hyleung** [comment]
@adriancole are there things that would be done differently (or more stuff that needs to be done) based on whether this goes into contrib or ASF? I haven't been following the ASF stuff that closely 🙈 - maybe I should get myself caught up.

**Comment by codefromthecrypt** [comment]
good question. most of the change is around release and that there is a
72hr waiting time needing votes. github issues and pull requests are still
fine.

we dont have experience with details in ASF for releases worked out yet. cc
@abesto @devinsba

**Comment by llinder** [comment]
I'm going to vote for moving this to openzipkin-contrib.  Moving to ASF is totally fine by me as well but I suspect it will take some work to move unless @hyleung and any other contributors have ICLA on file with ASF already.

**Comment by hyleung** [comment]
Just saw https://github.com/openzipkin-contrib/brave-ratpack!

What else needs to be wrapped up on this repo (if anything)?

**Comment by llinder** [comment]
Yes! Sorry I should have linked it here as well :/

Mostly just need to finish off release and snapshot publishing from Travis CI.  Right now I'm mostly following config from https://github.com/openzipkin-contrib/brave-opentracing so snapshots and releases should be similar once done.

🤞 I will get this done still yet today but if not definitely this week.

**Comment by llinder** [comment]
Snapshot build passed! https://travis-ci.org/openzipkin-contrib/brave-ratpack

@hyleung do you have anything you would like to see adjusted on the build?  Currently I have things configured to release artifacts to `io.zipkin.brave.ratpack:brave-ratpack`.  Does that GAV seem ok to folks? If everything looks ok I think the next step is to update the README with these changes and cut a release.

**Comment by hyleung** [comment]
Yay! Re. the GAV - don't have any particularly strong opinions, tho' having 'brave' and 'ratpack' in both the `GroupId` and the `ArtifiactId` seems redundant. Maybe something like `io.zipkin.contrib:brave-ratpack`? I dunno - naming is hard. 

I guess once you've cut a release, I can start looking at shuttering this project? You've got #67 on the go, but it probably makes more sense to carry on that work over in the new repo.

**Comment by codefromthecrypt** [comment]
one way or another we would need a separate group id as not everything in
contrib will have similar releasing etc (parent poms etc). I suggest the
former as even while strictly speaking contrib in the name might be good we
have no artifacts with contrib in the group id so far. non contrib will
soon be Apache anyway;)

**Comment by llinder** [comment]
Indeed naming is hard :) Besides Adrian's input, the reasons I didn't use `io.zipkin.contrib` was that the `brave-opentracing` library doesn't and coping from an existing project is easier than thinking ;) Also figured it would make a transition to Apache easier if that ever happens as we wouldn't have to change the GAV yet again.

I will move forward with the `io.zipkin.brave.ratpack:brave-ratpack` naming (and probably regret it in some way in the future).

Readme updates and release are now forthcoming :)

**Comment by llinder** [comment]
Done! https://search.maven.org/search?q=a:brave-ratpack 🎉

**Comment by hyleung** [comment]
@llinder yay! That being the case,  guess I can close this issue and update the README on this repo to let folks know they should be looking at the other repo :) Thanks for all your work on this!

**Comment by hyleung** [comment]
🎉Alright - the README is updated. If there aren't any objections, I'll archive this repo

**Comment by codefromthecrypt** [comment]
no objections here. good stuff!
